-- vim.keymap.set("n", "fd",":TablineBufferNext<CR>")
-- vim.keymap.set("n", "fa",":TablineBufferPrevious<CR>")
-- vim.keymap.set("n", "fc",":TablineBuffersClearBind<CR>")
--
-- vim.keymap.set("n", "sa",":tabnext<CR>")
-- vim.keymap.set("n", "sd",":tabprevious<CR>")
--
-- vim.keymap.set("n", "fr",":TablineTabRename ")
-- vim.keymap.set("n", "fw",":TablineTabNew<CR>")
--
